export const BACKGROUND_OPTIONS = {
    beliefs: [
      "You believe in and pray to a higher power (e.g., Vishnu, Jesus Christ, Haile Selassie I)",
      "Humanity needs no gods (e.g., Atheist, Humanist, Secularist)",
      "Science is the ultimate power! (e.g., Evolution, Cryonics, Space Exploration)",
      "It’s all about destiny (e.g., Karma, Caste System, Supernatural Forces)",
      "Member of a social or secret society (e.g., Freemasons, Women's Association, Anonymous)",
      "Society is broken, and you are its savior. What must be eradicated? (e.g., Drugs, Violence, Racism)",
      "Mystery persists (e.g., Astrology, Séance, Tarot Reading)",
      "Politics excites you (e.g., Conservative Party, Communist Party, Liberal Party)",
      "Money is power, and you will do anything to get it (e.g., Greed, Ambition, Ruthlessness)",
      "You’re a campaigner or activist (e.g., Feminist, Egalitarian, Union Rights Advocate)",
    ],
    importantPeople: [
      "Parent (e.g., Mother, Father, Stepmother)",
      "Grandparent (e.g., Grandmother, Grandfather)",
      "Sibling (e.g., Sister, Half-sister, Step-sister)",
      "Child (e.g., Son, Daughter)",
      "Significant Other (e.g., Spouse, Fiancé, Lover)",
      "Your mentor who taught you life skills (e.g., Teacher, Master, Father)",
      "Childhood friend (e.g., Classmate, Neighbor, Childhood Sweetheart)",
      "Celebrity idol or hero (e.g., Movie Star, Politician, Musician)",
      "Another investigator in the game (random or chosen)",
      "An NPC in the game (consult your Keeper for details)",
    ],
    reasons: [
      "You owe them a debt (e.g., Financial support, shelter in hard times, first job)",
      "They taught you something (e.g., A skill, how to love, how to be a man/woman)",
      "They gave your life meaning (e.g., You aspire to be like them, you seek their approval)",
      "You wronged them and seek redemption (e.g., Stole their money, betrayed them)",
      "Shared hardships (e.g., Survived war together, grew up together)",
      "You want to prove yourself to them (e.g., Find a job, marry, achieve a degree)",
      "You admire them (e.g., Their fame, charisma, or profession)",
      "Regretful feelings (e.g., You should have died in their place, you broke a promise)",
      "You try to outshine them (e.g., Their laziness, alcoholism, indifference)",
      "They disrupted your life, and you seek revenge (e.g., Murdered a loved one)",
    ],
    places: [
        "Your favorite school (e.g., High School, University)",
        "Your hometown (e.g., Rural village, Small town, Big city)",
        "The place you met your first love (e.g., Concert, Resort, Bomb shelter)",
        "A place for quiet reflection (e.g., Library, Cottage, Fishing spot)",
        "A social spot (e.g., Gentlemen's club, Local pub, Uncle's house)",
        "A location tied to your beliefs (e.g., Small chapel, Mecca, Stonehenge)",
        "The grave of an important person (e.g., Partner, Child, Lover)",
        "Your family’s residence (e.g., Rural house, Apartment, Orphanage of your youth)",
        "A place where you were the happiest (e.g., Park bench of your first kiss, Your university)",
        "Your workplace (e.g., Office, Library, Bank)",
      ],
      possessions: [
        "An item related to your skills (e.g., Fancy clothes, Fake ID, Brass knuckles)",
        "Essential tools of your profession (e.g., Medical kit, Car, Lockpick set)",
        "A keepsake from childhood (e.g., Comic book, Pocket knife, Lucky coin)",
        "A relic of a deceased person (e.g., Candelabra, Wallet with a photo, Letter)",
        "Something given by an important person (e.g., Ring, Journal, Map)",
        "A collectible (e.g., Tickets, Specimens, Records)",
        "Something you discovered but don’t understand (e.g., Letter in an unknown language, Mysterious organ inherited from your father, Strange silver sphere dug from your garden)",
        "Sports equipment (e.g., Baseball bat, Signed baseball, Fishing rod)",
        "A weapon (e.g., Semi-automatic revolver, Old hunting rifle, Boot knife)",
        "A pet (e.g., Dog, Cat, Turtle)",
      ],
      traits: [
        "Generous (e.g., Big tipper, Rainmaker, Philanthropist)",
        "Kind to animals (e.g., Cat lover, Raised on a farm, Dances with horses)",
        "Dreamer (e.g., Perpetual visionary, Fortune-teller, Creator)",
        "Hedonist (e.g., Party animal, Bar drunkard, 'Indulge till I drop')",
        "Gambler/Adventurer (e.g., Poker face, Try anything once, Lives on the edge)",
        "Good cook/Food lover (e.g., Great at baking, Can make a meal from nothing, Elegant gourmand)",
        "Charismatic (e.g., Smooth talker, Silver-tongued, Alluring presence)",
        "Loyal (e.g., Carries friends' burdens, Never breaks a vow, Dies for beliefs)",
        "Well-reputed (e.g., Village’s best storyteller, Devout saint, Fearless hero)",
        "Ambitious (e.g., Big dreams, Wants to be the boss, Seeks everything)",
      ],
};
  
