export const PROFESSIONS = {
    "Antiquarian": {
      title: "Antiquarian",
      skills: ["Appraise", "Art/Craft (Any)", "History", "Library Use", "Other Language", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Spot Hidden", "One Other Skill"],
      creditRating: "30-70",
      skillPoints: "EDU × 4",
      description: "Antiquarians are experts in studying and collecting historical artifacts. They excel in research, evaluation, and history.",
    },
    "Artist": {
      title: "Artist",
      skills: ["Art/Craft (Any)", "History or Natural World", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Other Language", "Psychology", "Spot Hidden", "Two Other Skills"],
      creditRating: "9-50",
      skillPoints: "EDU × 2 + POW × 2 or DEX × 2",
      description: "Artists are creative individuals skilled in producing art and navigating social interactions.",
    },
    "Athlete": {
      title: "Athlete",
      skills: ["Climb", "Jump", "Fighting (Brawl)", "Ride", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Swim", "Throw", "One Other Skill"],
      creditRating: "9-70",
      skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
      description: "Athletes are action-oriented investigators, excelling in physical prowess and endurance.",
    },
    "Writer": {
      title: "Writer",
      skills: ["Art/Craft (Literature)", "History", "Library Use", "Natural World or Occult", "Other Language", "Own Language", "Psychology", "One Other Skill"],
      creditRating: "9-30",
      skillPoints: "EDU × 4",
      description: "Writers are literary professionals skilled in crafting stories and researching complex topics.",
    },
    "Clergy": {
      title: "Clergy",
      skills: ["Accounting", "History", "Library Use", "Listen", "Other Language", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Psychology", "One Other Skill"],
      creditRating: "9-60",
      skillPoints: "EDU × 4",
      description: "Clergy members are spiritual leaders and scholars, often working with communities and ancient texts.",
    },
    "Criminal": {
      title: "Criminal",
      skills: ["One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Psychology", "Spot Hidden", "Stealth", "Choose Four: Appraise, Disguise, Fighting, Firearms, Locksmith, Mechanical Repair, Sleight of Hand"],
      creditRating: "5-65",
      skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
      description: "Criminals operate outside the law, excelling in deception, stealth, and other illicit skills.",
    },
    "Amateur Artist": {
      title: "Amateur Artist [Classic]",
      skills: ["Art/Craft (Any)", "Firearms", "Other Language", "Ride", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Three Other Skills"],
      creditRating: "50-99",
      skillPoints: "EDU × 2 + APP × 2",
      description: "Amateur artists are hobbyists who use their artistic talents alongside practical and social skills.",
    },
    "Doctor": {
      title: "Doctor",
      skills: ["First Aid", "Other Language (Latin)", "Medicine", "Psychology", "Science (Biology)", "Science (Pharmacy)", "Two Other Skills (Related to Expertise)"],
      creditRating: "30-80",
      skillPoints: "EDU × 4",
      description: "Doctors are professionals in medical fields, adept at treating injuries and studying science.",
    },
    "Drifter": {
      title: "Drifter",
      skills: ["Climb", "Jump", "Listen", "Navigate", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Stealth", "Two Other Skills"],
      creditRating: "0-5",
      skillPoints: "EDU × 2 + APP × 2 or DEX × 2 or STR × 2",
      description: "Drifters are wanderers with no fixed home, often skilled in navigation and survival.",
    },
    "Engineer": {
      title: "Engineer",
      skills: ["Art/Craft (Blueprints)", "Electrical Repair", "Library Use", "Mechanical Repair", "Operate Heavy Machinery", "Science (Engineering)", "Science (Physics)", "One Other Skill"],
      creditRating: "30-60",
      skillPoints: "EDU × 4",
      description: "Engineers are problem solvers and technical experts skilled in building and repairing complex systems.",
    },
    "Performer": {
      title: "Performer",
      skills: ["Art/Craft (Acting)", "Disguise", "Two Social Skills (Charm, Fast Talk, Intimidate, or Persuade)", "Listen", "Psychology", "Two Other Skills"],
      creditRating: "9-70",
      skillPoints: "EDU × 2 + APP × 2",
      description: "Performers captivate audiences with their skills in acting, social manipulation, and disguise.",
    },
    "Journalist": {
      title: "Journalist",
      skills: ["Art/Craft (Photography)", "History", "Library Use", "Other Language", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Psychology", "Two Other Skills"],
      creditRating: "9-30",
      skillPoints: "EDU × 4",
      description: "Journalists are skilled investigators who uncover the truth through interviews and research.",
    },
    "Farmer": {
      title: "Farmer",
      skills: ["Art/Craft (Farming)", "Drive Auto (or Animal Cart)", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Mechanical Repair", "Natural World", "Operate Heavy Machinery", "Track", "One Other Skill"],
      creditRating: "9-30",
      skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
      description: "Farmers are laborers skilled in agriculture and mechanical repair, with deep knowledge of nature and practical skills.",
    },
    "Hacker [Modern]": {
      title: "Hacker [Modern]",
      skills: ["Computer Use", "Electrical Repair", "Electronics", "Library Use", "Spot Hidden", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Two Other Skills"],
      creditRating: "10-70",
      skillPoints: "EDU × 4",
      description: "Hackers are modern experts in technology and electronics, specializing in digital systems and information retrieval.",
    },
    "Lawyer": {
      title: "Lawyer",
      skills: ["Accounting", "Law", "Library Use", "Two Social Skills (Charm, Fast Talk, Intimidate, or Persuade)", "Psychology", "Two Other Skills"],
      creditRating: "30-80",
      skillPoints: "EDU × 4",
      description: "Lawyers are legal professionals skilled in negotiation, research, and understanding complex legal systems.",
    },
    "Librarian [Classic]": {
      title: "Librarian [Classic]",
      skills: ["Accounting", "Library Use", "Other Language", "Own Language", "Four Skills Related to Personal Traits or Reading Specialization"],
      creditRating: "9-35",
      skillPoints: "EDU × 4",
      description: "Librarians are custodians of knowledge with expertise in languages, organization, and research.",
    },
    "Officer": {
      title: "Officer",
      skills: ["Accounting", "Firearms", "Navigate", "Two Social Skills (Charm, Fast Talk, Intimidate, or Persuade)", "Psychology", "Survival", "One Other Skill"],
      creditRating: "20-70",
      skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
      description: "Officers are trained leaders skilled in navigation, survival, and commanding others.",
    },
    "Missionary": {
      title: "Missionary",
      skills: ["Art/Craft (Any)", "Mechanical Repair", "Medicine", "Natural World", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Two Other Skills"],
      creditRating: "0-30",
      skillPoints: "EDU × 4",
      description: "Missionaries are compassionate individuals focused on helping others, often in remote or challenging environments.",
    },
    "Musician": {
      title: "Musician",
      skills: ["Art/Craft (Musical Instrument)", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Listen", "Psychology", "Four Other Skills"],
      creditRating: "9-30",
      skillPoints: "EDU × 2 + DEX × 2 or POW × 2",
      description: "Musicians are artists skilled in performing and interpreting music, often possessing keen social awareness.",
    },
    "Parapsychologist": {
      title: "Parapsychologist",
      skills: ["Anthropology", "Art/Craft (Photography)", "History", "Library Use", "Occult", "Other Language", "Psychology", "One Other Skill"],
      creditRating: "9-30",
      skillPoints: "EDU × 4",
      description: "Parapsychologists investigate supernatural phenomena using scientific methods and an understanding of the occult.",
    },
    "Pilot": {
      title: "Pilot",
      skills: ["Electrical Repair", "Mechanical Repair", "Navigate", "Operate Heavy Machinery", "Drive (Aircraft)", "Science (Astronomy)", "Two Other Skills"],
      creditRating: "20-70",
      skillPoints: "EDU × 2 + DEX × 2",
      description: "Pilots are skilled navigators and operators of aircraft, often with technical expertise in mechanical systems.",
    },
    "Detective": {
      title: "Detective",
      skills: ["Art/Craft (Acting) or Disguise", "Firearms", "Law", "Listen", "One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)", "Psychology", "Spot Hidden", "One Other Skill"],
      creditRating: "20-50",
      skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
      description: "Detectives are law enforcement experts, skilled in investigating crimes and interrogating suspects.",
    },
    "Police Officer": {
      title: "Police Officer",
      skills: ["Fighting (Brawl)","Firearms","First Aid","One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)","Law","Psychology","Spot Hidden","Drive Auto or Ride"],
      creditRating: "9-30",
      skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
      description: "Police officers are enforcers of the law, skilled in combat, investigation, and emergency response.",
    },
    "Private Investigator": {
      title: "Private Investigator",
      skills: ["Art/Craft (Photography)","Disguise","Law","Library Use","One Social Skill (Charm, Fast Talk, Intimidate, or Persuade)","Psychology","Spot Hidden","One Other Skill (e.g., Computer Use, Locksmith, Firearms)"],
      creditRating: "9-30",
      skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
      description: "Private investigators are skilled detectives who use their wits and tools to uncover the truth.",
    },
    "Professor [Classic]": {
      title: "Professor [Classic]",
      skills: ["Library Use","Other Language","Own Language","Psychology","Four Skills Related to Academic or Personal Expertise"],
      creditRating: "20-70",
      skillPoints: "EDU × 4",
      description: "Professors are scholarly experts, highly educated and specialized in their chosen fields.",
    },
    "Soldier": {
      title: "Soldier",
      skills: ["Climb or Swim", "Dodge", "Fighting", "Firearms", "Stealth", "Survival", "Two Other Skills (e.g., First Aid, Mechanical Repair, Other Language)"],
      creditRating: "9-30",
      skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
      description: "Soldiers are trained fighters skilled in combat and survival techniques.",
    },
    "Tribal Member": {
      title: "Tribal Member",
      skills: ["Climb", "Fighting or Throw", "Natural World", "Listen", "Occult", "Spot Hidden", "Swim", "Survival (Any)"],
      creditRating: "0-15",
      skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
      description: "Tribal members are deeply connected to nature and spiritual practices, excelling in survival and combat.",
    },
    "Zealot": {
      title: "Zealot",
      skills: ["History", "Two Social Skills (Charm, Fast Talk, Intimidate, or Persuade)", "Psychology", "Stealth", "Three Other Skills"],
      creditRating: "0-30",
      skillPoints: "EDU × 2 + APP × 2 or POW × 2",
      description: "Zealots are driven individuals dedicated to their beliefs, excelling in persuasion and stealth.",
    },
    
  };