export const PROFESSIONS = {
  "Antiquarian": {
    key: "Antiquarian",
    title: "Antiquarian",
    skills: ["History", "Art"],
    creditRating: "30-70",
    skillPoints: "EDU × 4",
    description: "I am an expert specializing in historical artifacts research. With deep knowledge of history and art appreciation skills, I can accurately evaluate and analyze the value and historical significance of various antiques.",
  },
  "Artist": {
    key: "Artist",
    title: "Artist",
    skills: ["Art", "Craft"],
    creditRating: "9-50", 
    skillPoints: "EDU × 2 + LUCK × 2",
    description: "I am a creator pursuing artistic perfection. My skilled hands can transform inspiration into touching artworks, and I'm good at communicating with people through my works.",
  },
  "Clergy": {
    key: "Clergy",
    title: "Clergy",
    skills: ["Occult", "Communication", "Psychology"],
    creditRating: "9-60",
    skillPoints: "EDU × 4",
    description: "I am a devout spreader of faith. Through my study of the occult, excellent communication skills, and deep understanding of human nature, I guide believers to find spiritual comfort.",
  },
  "Criminal": {
    key: "Criminal",
    title: "Criminal",
    skills: ["Sleight of Hand", "Firearms", "Fighting", "Dodge"],
    creditRating: "5-65",
    skillPoints: "EDU × 2 + DEX × 2",
    description: "I am a shadow figure walking on the edge of law. Proficient in sleight of hand and various weapons, I can always rely on my agility to escape in dangerous moments.",
  },
  "Doctor": {
    key: "Doctor",
    title: "Doctor",
    skills: ["Medicine", "First Aid", "Science"],
    creditRating: "30-80",
    skillPoints: "EDU × 4",
    description: "I am a professional medical worker. Relying on solid medical knowledge, skilled surgical techniques, and scientific thinking, I am dedicated to healing patients and saving lives.",
  },
  "Engineer": {
    key: "Engineer",
    title: "Engineer",
    skills: ["Mechanical", "Science", "Electronics"],
    creditRating: "30-60",
    skillPoints: "EDU × 4",
    description: "I am a technically proficient problem solver. With deep understanding of mechanics, science, and electronics, I can design, build, and repair various complex systems.",
  },
  "Performer": {
    key: "Performer",
    title: "Performer",
    skills: ["Communication", "Psychology", "Art"],
    creditRating: "9-70",
    skillPoints: "EDU × 2 + APP × 2",
    description: "I am a master performer on stage. Through insight into human nature and excellent artistic expression, I can win audience applause in various occasions.",
  },
  "Farmer": {
    key: "Farmer",
    title: "Farmer",
    skills: ["Firearms", "Drive", "Communication", "Spot Hidden"],
    creditRating: "9-30",
    skillPoints: "DEX × 2 + STR × 2",
    description: "I am an experienced farm operator. Proficient in farming machinery operation and maintenance, good at observing weather changes, and skilled in dealing with people. When necessary, I can also use guns to protect my property.",
  },
  "Hacker": {
    key: "Hacker",
    title: "Hacker",
    skills: ["Electronics", "Spot Hidden"],
    creditRating: "10-70",
    skillPoints: "EDU × 4",
    description: "I am an explorer of the digital world. Through excellent electronic skills and keen observation, I can penetrate the core of any digital system.",
  },
  "Journalist": {
    key: "Journalist",
    title: "Journalist",
    skills: ["Communication", "Psychology", "Spot Hidden"],
    creditRating: "9-30",
    skillPoints: "EDU × 4",
    description: "I am a truth-seeking journalist. With excellent communication skills, insight into human nature, and meticulous investigation techniques, I am committed to revealing the truth of every event.",
  },
  "Lawyer": {
    key: "Lawyer",
    title: "Lawyer",
    skills: ["Communication", "Library Use", "Psychology"],
    creditRating: "30-80",
    skillPoints: "EDU × 4",
    description: "I am a law expert defender. Through rich legal knowledge, excellent communication skills, and understanding of human nature, I strive for maximum legal rights for my clients.",
  },
  "Librarian": {
    key: "Librarian",
    title: "Librarian",
    skills: ["Library Use", "Science", "Occult"],
    creditRating: "9-35",
    skillPoints: "EDU × 4",
    description: "I am a guardian and guide of knowledge. Proficient in book classification and retrieval, with in-depth research in both science and occult studies, I can help people find any information they need.",
  },
  "Officer": {
    key: "Officer",
    title: "Officer",
    skills: ["Communication", "Firearms", "Psychology"],
    creditRating: "20-70",
    skillPoints: "EDU × 2 + DEX × 2",
    description: "I am an experienced military commander. Proficient in firearms use, good at leading and motivating subordinates, able to accurately grasp battlefield situations and personnel psychology.",
  },
  "Zealot": {
    key: "Zealot",
    title: "Zealot",
    skills: ["Occult", "Psychology", "Dodge"],
    creditRating: "0-70",
    skillPoints: "EDU × 2 + POW × 2",
    description: "I am a fanatical follower of faith. Well-versed in occult knowledge, good at observing and influencing others' psychology, always able to turn danger into safety in dangerous moments.",
  },
  "Detective": {
    key: "Detective",
    title: "Detective",
    skills: ["Spot Hidden", "Psychology", "Firearms", "Communication"],
    creditRating: "20-50",
    skillPoints: "EDU × 2 + STR × 2",
    description: "I am a professional criminal investigator. With keen insight, understanding of criminal psychology, and rich case-handling experience, I can solve various complex cases.",
  },
  "PoliceOfficer": {
    key: "PoliceOfficer",
    title: "Police Officer",
    skills: ["Drive", "Firearms", "Fighting"],
    creditRating: "9-30",
    skillPoints: "POW × 2 + STR × 2",
    description: "I am a dedicated law enforcement officer. Proficient in driving and various weapons use, able to quickly respond and handle various emergencies.",
  },
  "PrivateInvestigator": {
    key: "PrivateInvestigator",
    title: "Private Investigator",
    skills: ["Spot Hidden", "Stealth", "Communication", "Psychology"],
    creditRating: "9-30",
    skillPoints: "EDU × 2 + DEX × 2",
    description: "I am an independent truth seeker. Through careful observation, covert tracking, and clever conversation, I can discover and reveal various hidden secrets.",
  },
  "Professor": {
    key: "Professor",
    title: "Professor",
    skills: ["Library Use", "Psychology"],
    creditRating: "20-70",
    skillPoints: "EDU × 4",
    description: "I am a learned scholar. Proficient in literature retrieval, well-versed in educational psychology, with unique insights and research achievements in my professional field.",
  },
  "Soldier": {
    key: "Soldier",
    title: "Soldier",
    skills: ["Fighting", "Dodge", "Firearms"],
    creditRating: "9-30",
    skillPoints: "POW × 2 + STR × 2",
    description: "I am a well-trained warrior. Proficient in various combat skills, able to quickly react and make correct judgments when facing danger.",
  },
  "TribalMember": {
    key: "TribalMember",
    title: "Tribal Member",
    skills: ["Occult", "Spot Hidden", "Fighting"],
    creditRating: "0-15",
    skillPoints: "EDU × 2 + LUCK × 2",
    description: "I am a tribal member closely connected with nature. Proficient in ancient mystical rituals, with keen observation skills and excellent survival abilities.",
  },
};