// export const PROFESSIONS = {
//   "Antiquarian": {
//     title: "Antiquarian",
//     skills: ["History", "Art"],
//     creditRating: "30-70",
//     skillPoints: "EDU × 4",
//     description: "Antiquarians are experts in studying and collecting historical artifacts. They excel in research, evaluation, and history.",
//   },
//   "Artist": {
//     title: "Artist",
//     skills: ["Art", "Craft"],
//     creditRating: "9-50",
//     skillPoints: "EDU × 2 + POW × 2 or DEX × 2",
//     description: "Artists are creative individuals skilled in producing art and navigating social interactions.",
//   },
//   "Clergy": {
//     title: "Clergy",
//     skills: ["Occult", "Social", "Psychology"],
//     creditRating: "9-60",
//     skillPoints: "EDU × 4",
//     description: "Clergy members are spiritual leaders and scholars, often working with communities and ancient texts.",
//   },
//   "Criminal": {
//     title: "Criminal",
//     skills: ["Craft", "Firearms", "Fighting", "Dodge"],
//     creditRating: "5-65",
//     skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
//     description: "Criminals operate outside the law, excelling in deception, stealth, and other illicit skills.",
//   },
//   "Doctor": {
//     title: "Doctor",
//     skills: ["Medicine", "Craft", "Science"],
//     creditRating: "30-80",
//     skillPoints: "EDU × 4",
//     description: "Doctors are professionals in medical fields, adept at treating injuries and studying science.",
//   },
//   "Engineer": {
//     title: "Engineer",
//     skills: ["Mechanical", "Science", "Electronics"],
//     creditRating: "30-60",
//     skillPoints: "EDU × 4",
//     description: "Engineers are problem solvers and technical experts skilled in building and repairing complex systems.",
//   },
//   "Performer": {
//     title: "Performer",
//     skills: ["Social", "Psychology", "Art"],
//     creditRating: "9-70",
//     skillPoints: "EDU × 2 + APP × 2",
//     description: "Performers captivate audiences with their skills in acting, social manipulation, and disguise.",
//   },
//   "Farmer": {
//     title: "Farmer",
//     skills: ["Firearms", "Driving", "Social", "Spot Hidden"],
//     creditRating: "9-30",
//     skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
//     description: "Farmers are laborers skilled in agriculture and mechanical repair, with deep knowledge of nature and practical skills.",
//   },
//   "Hacker": {
//     title: "Hacker",
//     skills: ["Electronics", "Spot Hidden"],
//     creditRating: "10-70",
//     skillPoints: "EDU × 4",
//     description: "Hackers are modern experts in technology and electronics, specializing in digital systems and information retrieval.",
//   },
//   "Journalist": {
//     title: "Journalist",
//     skills: ["Social", "Psychology", "Spot Hidden"],
//     creditRating: "9-30",
//     skillPoints: "EDU × 4",
//     description: "Journalists are skilled investigators who uncover the truth through interviews and research.",
//   },
//   "Lawyer": {
//     title: "Lawyer",
//     skills: ["Social", "Library Use", "Psychology"],
//     creditRating: "30-80",
//     skillPoints: "EDU × 4",
//     description: "Lawyers are legal professionals skilled in negotiation, research, and understanding complex legal systems.",
//   },
//   "Librarian": {
//     title: "Librarian",
//     skills: ["Library Use", "Science", "Occult"],
//     creditRating: "9-35",
//     skillPoints: "EDU × 4",
//     description: "Librarians are custodians of knowledge with expertise in languages, organization, and research.",
//   },
//   "Officer": {
//     title: "Officer",
//     skills: ["Social", "Firearms", "Psychology"],
//     creditRating: "20-70",
//     skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
//     description: "Officers are trained leaders skilled in navigation, survival, and commanding others.",
//   },
//   "Zealot": {
//     title: "Zealot",
//     skills: ["Occult", "Psychology", "Dodge"],
//     creditRating: "0-30",
//     skillPoints: "EDU × 2 + APP × 2 or POW × 2",
//     description: "Zealots are driven individuals dedicated to their beliefs, excelling in persuasion and stealth.",
//   },
//   "Detective": {
//     title: "Detective",
//     skills: ["Spot Hidden", "Psychology", "Firearms", "Social"],
//     creditRating: "20-50",
//     skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
//     description: "Detectives are law enforcement experts, skilled in investigating crimes and interrogating suspects.",
//   },
//   "PoliceOfficer": {
//     title: "Police Officer",
//     skills: ["Driving", "Firearms", "Fighting"],
//     creditRating: "9-30",
//     skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
//     description: "Police officers are enforcers of the law, skilled in combat, investigation, and emergency response.",
//   },
//   "PrivateInvestigator": {
//     title: "Private Investigator",
//     skills: ["Spot Hidden", "Stealth", "Social", "Psychology"],
//     creditRating: "9-30",
//     skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
//     description: "Private investigators are skilled detectives who use their wits and tools to uncover the truth.",
//   },
//   "Professor": {
//     title: "Professor",
//     skills: ["Library Use", "Psychology"],
//     creditRating: "20-70",
//     skillPoints: "EDU × 4",
//     description: "Professors are scholarly experts, highly educated and specialized in their chosen fields.",
//   },
//   "Soldier": {
//     title: "Soldier",
//     skills: ["Fighting", "Dodge", "Firearms"],
//     creditRating: "9-30",
//     skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
//     description: "Soldiers are trained fighters skilled in combat and survival techniques.",
//   },
//   "TribalMember": {
//     title: "Tribal Member",
//     skills: ["Occult", "Spot Hidden", "Fighting"],
//     creditRating: "0-15",
//     skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
//     description: "Tribal members are deeply connected to nature and spiritual practices, excelling in survival and combat.",
//   },
// };
export const PROFESSIONS = {
  "Antiquarian": {
    title: "Antiquarian",
    skills: ["History", "Art"],
    creditRating: "30-70",
    skillPoints: "EDU × 4",
    description: "I am an expert in studying and collecting historical artifacts. My passion lies in research, evaluation, and uncovering history's secrets.",
  },
  "Artist": {
    title: "Artist",
    skills: ["Art", "Craft"],
    creditRating: "9-50",
    skillPoints: "EDU × 2 + POW × 2 or DEX × 2",
    description: "I create and express myself through my art. My skills also help me navigate social interactions and bring my visions to life.",
  },
  "Clergy": {
    title: "Clergy",
    skills: ["Occult", "Social", "Psychology"],
    creditRating: "9-60",
    skillPoints: "EDU × 4",
    description: "I am a spiritual leader, dedicated to my community and the pursuit of ancient knowledge.",
  },
  "Criminal": {
    title: "Criminal",
    skills: ["Craft", "Firearms", "Fighting", "Dodge"],
    creditRating: "5-65",
    skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
    description: "I live outside the law, relying on my skills in deception, stealth, and combat to survive.",
  },
  "Doctor": {
    title: "Doctor",
    skills: ["Medicine", "Craft", "Science"],
    creditRating: "30-80",
    skillPoints: "EDU × 4",
    description: "I dedicate myself to healing others and advancing medical knowledge through science.",
  },
  "Engineer": {
    title: "Engineer",
    skills: ["Mechanical", "Science", "Electronics"],
    creditRating: "30-60",
    skillPoints: "EDU × 4",
    description: "I solve problems and create solutions using my expertise in engineering and technical systems.",
  },
  "Performer": {
    title: "Performer",
    skills: ["Social", "Psychology", "Art"],
    creditRating: "9-70",
    skillPoints: "EDU × 2 + APP × 2",
    description: "I captivate audiences with my performances and use my charm to navigate any social situation.",
  },
  "Farmer": {
    title: "Farmer",
    skills: ["Firearms", "Driving", "Social", "Spot Hidden"],
    creditRating: "9-30",
    skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
    description: "I am a laborer of the land, skilled in agriculture, repair, and understanding the natural world.",
  },
  "Hacker": {
    title: "Hacker",
    skills: ["Electronics", "Spot Hidden"],
    creditRating: "10-70",
    skillPoints: "EDU × 4",
    description: "I thrive in the digital realm, breaking into systems and uncovering hidden truths with my technical skills.",
  },
  "Journalist": {
    title: "Journalist",
    skills: ["Social", "Psychology", "Spot Hidden"],
    creditRating: "9-30",
    skillPoints: "EDU × 4",
    description: "I uncover the truth through interviews, research, and a relentless pursuit of stories.",
  },
  "Lawyer": {
    title: "Lawyer",
    skills: ["Social", "Library Use", "Psychology"],
    creditRating: "30-80",
    skillPoints: "EDU × 4",
    description: "I am a skilled negotiator and researcher, dedicated to understanding and practicing the law.",
  },
  "Librarian": {
    title: "Librarian",
    skills: ["Library Use", "Science", "Occult"],
    creditRating: "9-35",
    skillPoints: "EDU × 4",
    description: "I am the keeper of knowledge, specializing in research, organization, and understanding obscure subjects.",
  },
  "Officer": {
    title: "Officer",
    skills: ["Social", "Firearms", "Psychology"],
    creditRating: "20-70",
    skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
    description: "I lead others with discipline and skill, navigating survival situations and commanding respect.",
  },
  "Zealot": {
    title: "Zealot",
    skills: ["Occult", "Psychology", "Dodge"],
    creditRating: "0-30",
    skillPoints: "EDU × 2 + APP × 2 or POW × 2",
    description: "I am driven by my beliefs, using my cunning and resolve to spread my message and achieve my goals.",
  },
  "Detective": {
    title: "Detective",
    skills: ["Spot Hidden", "Psychology", "Firearms", "Social"],
    creditRating: "20-50",
    skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
    description: "I am an investigator, skilled in solving mysteries and interrogating suspects.",
  },
  "PoliceOfficer": {
    title: "PoliceOfficer",
    skills: ["Driving", "Firearms", "Fighting"],
    creditRating: "9-30",
    skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
    description: "I enforce the law with strength and precision, ready to respond to any emergency.",
  },
  "PrivateInvestigator": {
    title: "PrivateInvestigator",
    skills: ["Spot Hidden", "Stealth", "Social", "Psychology"],
    creditRating: "9-30",
    skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
    description: "I uncover secrets and solve puzzles, using my wits and resourcefulness to reveal the truth.",
  },
  "Professor": {
    title: "Professor",
    skills: ["Library Use", "Psychology"],
    creditRating: "20-70",
    skillPoints: "EDU × 4",
    description: "I am an academic expert, dedicated to teaching, research, and intellectual pursuits.",
  },
  "Soldier": {
    title: "Soldier",
    skills: ["Fighting", "Dodge", "Firearms"],
    creditRating: "9-30",
    skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
    description: "I am a trained fighter, skilled in combat and survival under any conditions.",
  },
  "TribalMember": {
    title: "TribalMember",
    skills: ["Occult", "Spot Hidden", "Fighting"],
    creditRating: "0-15",
    skillPoints: "EDU × 2 + DEX × 2 or STR × 2",
    description: "I am deeply connected to nature and tradition, excelling in survival and spiritual practices.",
  },
};
